server:
  host: ${MCP_HOST:0.0.0.0}
  port: ${MCP_PORT:4242}
  log_level: ${MCP_LOG_LEVEL:INFO}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  db: ${REDIS_DB:0}

joern:
  binary_path: ${JOERN_BINARY_PATH:joern}
  memory_limit: ${JOERN_MEMORY_LIMIT:4g}

sessions:
  ttl: ${SESSION_TTL:3600}
  idle_timeout: ${SESSION_IDLE_TIMEOUT:1800}
  max_concurrent: ${MAX_CONCURRENT_SESSIONS:50}

cpg:
  generation_timeout: ${CPG_GENERATION_TIMEOUT:600}
  max_repo_size_mb: ${MAX_REPO_SIZE_MB:500}
  supported_languages:
    - java
    - c
    - cpp
    - javascript
    - python
    - go
    - kotlin
    - csharp
    - ghidra
    - jimple
    - php
    - ruby
    - swift
  exclusion_patterns:
    # Hidden files and directories (starting with .)
    - ".*/\\..*"
    - "\\..*"
    
    # Test and fuzzing directories (both root level and nested, with wildcards)
    - ".*/test.*"
    - "test.*"
    - ".*/fuzz.*"
    - "fuzz.*"
    - ".*/Testing.*"
    - "Testing.*"
    - ".*/spec.*"
    - "spec.*"
    - ".*/__tests__/.*"
    - "__tests__/.*"
    - ".*/e2e.*"
    - "e2e.*"
    - ".*/integration.*"
    - "integration.*"
    - ".*/unit.*"
    - "unit.*"
    - ".*/benchmark.*"
    - "benchmark.*"
    - ".*/perf.*"
    - "perf.*"
    
    # Documentation and examples (both root level and nested, with wildcards)
    - ".*/docs?/.*"
    - "docs?/.*"
    - ".*/documentation.*"
    - "documentation.*"
    - ".*/example.*"
    - "example.*"
    - ".*/sample.*"
    - "sample.*"
    - ".*/demo.*"
    - "demo.*"
    - ".*/tutorial.*"
    - "tutorial.*"
    - ".*/guide.*"
    - "guide.*"
    
    # Build and development artifacts
    - ".*/build.*/.*"
    - ".*_build/.*"
    - ".*/target/.*"
    - ".*/out/.*"
    - ".*/dist/.*"
    - ".*/bin/.*"
    - ".*/obj/.*"
    - ".*/Debug/.*"
    - ".*/Release/.*"
    - ".*/cmake/.*"
    - ".*/m4/.*"
    - ".*/autom4te.*/.*"
    - ".*/autotools/.*"
    
    # Version control and dependencies
    - ".*/\\.git/.*"
    - ".*/\\.svn/.*"
    - ".*/\\.hg/.*"
    - ".*/\\.deps/.*"
    - ".*/node_modules/.*"
    - ".*/vendor/.*"
    - ".*/third_party/.*"
    - ".*/extern/.*"
    - ".*/external/.*"
    - ".*/packages/.*"
    
    # Performance and profiling
    - ".*/benchmark.*/.*"
    - ".*/perf.*/.*"
    - ".*/profile.*/.*"
    - ".*/bench/.*"
    
    # Tools and scripts  
    - ".*/tool.*/.*"
    - ".*/script.*/.*"
    - ".*/utils/.*"
    - ".*/util/.*"
    - ".*/helper.*/.*"
    - ".*/misc/.*"
    
    # Language-specific binding/wrapper directories
    - ".*/python/.*"
    - ".*/java/.*"
    - ".*/ruby/.*"
    - ".*/perl/.*"
    - ".*/php/.*"
    - ".*/csharp/.*"
    - ".*/dotnet/.*"
    - ".*/go/.*"
    
    # Generated and temporary files
    - ".*/generated/.*"
    - ".*/gen/.*"
    - ".*/temp/.*"
    - ".*/tmp/.*"
    - ".*/cache/.*"
    - ".*/\\.cache/.*"
    - ".*/log.*/.*"
    - ".*/logs/.*"
    - ".*/result.*/.*"
    - ".*/results/.*"
    - ".*/output/.*"
    
    # Configuration and metadata files (by extension)
    - ".*\\.md$"
    - ".*\\.txt$"
    - ".*\\.xml$"
    - ".*\\.json$"
    - ".*\\.yaml$"
    - ".*\\.yml$"
    - ".*\\.toml$"
    - ".*\\.ini$"
    - ".*\\.cfg$"
    - ".*\\.conf$"
    - ".*\\.properties$"
    - ".*\\.cmake$"
    - ".*Makefile.*"
    - ".*makefile.*"
    - ".*configure.*"
    - ".*\\.am$"
    - ".*\\.in$"
    - ".*\\.ac$"
    - ".*\\.log$"
    - ".*\\.cache$"
    - ".*\\.lock$"
    - ".*\\.tmp$"
    - ".*\\.bak$"
    - ".*\\.orig$"
    - ".*\\.swp$"
    - ".*~$"
    
    # IDE and editor files
    - ".*/\\.vscode/.*"
    - ".*/\\.idea/.*"
    - ".*/\\.eclipse/.*"
    - ".*\\.DS_Store$"
    - ".*Thumbs\\.db$"
  
  languages_with_exclusions:
    - c
    - cpp
    - java
    - javascript
    - python
    - go
    - kotlin
    - csharp
    - php
    - ruby

query:
  timeout: ${QUERY_TIMEOUT:30}
  cache_enabled: ${QUERY_CACHE_ENABLED:true}
  cache_ttl: ${QUERY_CACHE_TTL:300}

storage:
  workspace_root: ${WORKSPACE_ROOT:/tmp/joern-mcp}
  cleanup_on_shutdown: ${CLEANUP_ON_SHUTDOWN:true}